routes/backend.php
<?php

  Route::group(['namespace' => '\\Backend\\Auth'], function() {

      Route::get('login', 'LoginController@showLoginForm')->name('admin.showLogin');
      Route::post('login', 'LoginController@login')->name('admin.postLogin');
      Route::get('logout', 'LoginController@logout')->name('admin.logout')->middleware('admin.auth' );

  });

  Route::group(['middleware' => 'admin.auth','namespace' => 'Backend'], function() {
      Route::get('/', [
          'as'   => 'admin.home',
          'uses' => 'DashboardController@index'
      ]);
      Route::get('user/profile','UserController@profile')->name('user.profile');
      Route::put('user/profile/{user}','UserController@updateProfile')->name('user.updateProfile');
      Route::resource('user','UserController');
      Route::resource('permission','PermissionController');
      Route::resource('role','RoleController');

      Route::resource('bus','BusController');
      Route::get('busstop/export','BusStopController@getExportExcel')->name('busstop.export');
      Route::post('busstop/quickUpdate','BusStopController@quickUpdate')->name('busstop.quickUpdate');
      Route::post('busstop/data','BusStopController@data');
      Route::resource('busstop','BusStopController');

      Route::get('route/export','BusRouteController@getExportExcel')->name('route.export');
      Route::post('route/map','BusRouteController@getMap')->name('route.map');

      Route::resource('route','BusRouteController');

      Route::get('township/list','TownshipController@getTownshipList');
      Route::resource('township','TownshipController');

      Route::get('gate/list','BusGateController@getGateList');
      Route::resource('gate','BusGateController');

      Route::get('gatekeeper/list','GateKeeperController@getGateKeeperList');
      Route::resource('gatekeeper','GateKeeperController');

      Route::get('gateregister/list','GateRegisterController@getGateRegisterList');
      Route::resource('gateregister','GateRegisterController');

      Route::get('busstate/list','BusStateController@getBusStateList');
      Route::resource('busstate','BusStateController');

      Route::get('street/list','StreetController@getStreetList');
      Route::resource('street','StreetController');
  });

routes/web.php
<?php

Route::get('/',function() {
  return redirect('/admin');
});

app/Http/Controllers/Backend/Api/ApiController.php
<?php

namespace App\Http\Controllers\Backend\Api;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Response;
/**
 * Class ApiController
 *
 * @package \Techcode\Api\Controller
 */
class ApiController extends Controller
{
    /**
     * @var int
     */
    protected $statusCode = 200;

    /**
     * @return int
     */
    public function getStatusCode()
    {
        return $this->statusCode;
    }

    /**
     * @param $statusCode
     *
     * @return $this
     */
    public function setStatusCode($statusCode)
    {
        $this->statusCode = $statusCode;
        return $this;
    }


    /**
     * @param       $data
     * @param array $headers
     *
     * @return mixed
     */
    public function respond($data, $headers = [])
    {
        return Response::json($data,$this->getStatusCode(),$headers);
    }


    /**
     * @param string $message
     *
     * @return mixed
     */
    public function respondNotFound($message = 'Not Found')
    {
       return $this->setStatusCode(404)->respondWithError($message);
    }


    /**
     * @param string $message
     *
     * @return mixed
     */
    public function respondInternalError($message = 'Internal Server Error')
    {
        return $this->setStatusCode(500)->respondWithError($message);
    }


    /**
     * @param $message
     *
     * @return mixed
     */
    public function respondWithError($message)
    {
        return $this->respond([
            'error' => [
                'message'       => $message,
                'status_code'   => $this->getStatusCode()
            ]
        ]);
    }


}

app/Http/Controllers/Backend/Api/BusApiController.php
<?php namespace App\Http\Controllers\Backend\Api;


use App\Transformers\BusTransformer;
use App\Transformers\BusRouteTransformer;
use Illuminate\Http\Request;
use App\Bus;
use App\BusStop;
use Carbon\Carbon;

class BusApiController extends ApiController
{
    protected $busTransformer;
    protected $busRouteTransformer;

    public function __construct(BusTransformer $busTransformer, BusRouteTransformer $busRouteTransformer)
    {
        $this->busTransformer    = $busTransformer;
        $this->busRouteTransformer    = $busRouteTransformer;
    }


    public function index(Request $request)
    {
        $bus = Bus::with('busstops')->get();
        return $this->respond([
            'data' => $this->busTransformer->transformCollection($bus->all())
      ]);
    }

    public function getBusRoutes(Request $request)
    {
        $name = $request->get('bus_name');
        $bus = Bus::where('name',$name)->first();
        if(! $bus){
           return $this->respondNotFound('Bus not found!');
        }
        $route_start_to_end = $bus->busstops()->wherePivot('type','F')->orderBy('pivot_order', 'asc')->get()->toArray();
        $route_end_to_start = $bus->busstops()->wherePivot('type','R')->orderBy('pivot_order', 'asc')->get()->toArray();
        return $this->respond([
            'data' => [
                'route_start_to_end' => $this->busRouteTransformer->transformCollection($route_start_to_end),
                'route_end_to_start' => $this->busRouteTransformer->transformCollection($route_end_to_start)
            ],
        ]);
    }

    public function getUpdatedTime()
    {
        $bus = Bus::orderBy('updated_at','DESC')->first();
        $bus_stop = BusStop::orderBy('updated_at','DESC')->first();
        return $this->respond([
            'updated_at' => $bus->updated_at->toDateTimeString(),
            'busstop_updated_at' => $bus_stop->updated_at->toDateTimeString(),
        ]);
    }
}

app/Http/Controllers/Backend/Api/BusStopApiController.php
<?php namespace App\Http\Controllers\Backend\Api;


use App\Transformers\BusStopTransformer;
use Illuminate\Http\Request;
use App\BusStop;

class BusStopApiController extends ApiController
{
    protected $busStopTransformer;

    public function __construct(BusStopTransformer $busStopTransformer)
    {
        $this->busStopTransformer    = $busStopTransformer;
    }


    public function index(Request $request)
    {
        $busstops = BusStop::all();
        return $this->respond([
        'data' => $this->busStopTransformer->transformCollection($busstops->all())
      ]);
    }


}

app/Http/Controllers/Backend/Api/DeviceApiController.php
<?php namespace App\Http\Controllers\Backend\Api;


use Illuminate\Http\Request;

class DeviceApiController extends GuzzleClient
{
    protected $api_url = 'StandardApiAction_getDeviceStatus.action?';

    protected $vehiIdno;

    function __construct(Request $request)
    {
      parent::__construct();
      parent::__construct();
      $user = $request->get('user');
      $password = $request->get('password');
      if ($user && $password) {
        $this->login($user,$password);
      }else{
        $ret = ['status' => 'fail','msg' => 'Unauthorize access.Please check user name and password!'];
        echo json_encode($ret);
      }
      $this->vehiIdno = $request->get('vehiIdno');
      if ( empty($this->vehiIdno)) {
          $ret = ['status' => 'fail','msg' => 'Unauthorize access.vehiIdno must include in request'];
          echo json_encode($ret);  
      }
    }

    public function index()
    {
      $response = $this->client->get($this->api_url,['query' => [
          'jsession'  => $this->jsession,
          'vehiIdno'   => $this->vehiIdno
        ]]);
      $data = $response->getBody();

      echo $data;
    }
}

app/Http/Controllers/Backend/Api/GateRegisterApiController.php
<?php

namespace App\Http\Controllers\Backend\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\GateRegister;
use App\GateKeeper;
use App\BusGate;
use App\BusState;
class GateRegisterApiController extends ApiController
{
    //

    public function index()
    {

    }

    public function BusRegisterGate(Request $request)
    {

    	$data = [
    		'gateRegister_serviceNo' => $request->get('gateRegister_serviceNo'),
    		"gateRegister_userid" => $request->get('gateRegister_userid'),
    		"gateRegister_gateid" => $request->get('gateRegister_gateid'),
    		"gateRegister_time" =>$request->get('gateRegister_time'),
    		"gateRegister_inout"  =>$request->get('gateRegister_inout'),
    		"gateRegister_busNo"  =>$request->get('gateRegister_busNo'),
            'gateRegister_isArrive' => $request->get('gateRegister_isArrive'),
    		"gateRegister_date"   => $request->get('gateRegister_date')
    	];

    	$gate = GateRegister::create($data);

    	if(! $gate){
           return $this->respondNotFound('Not Success');
        }
    	return $this->respond([
    		'data' => [
                'status' => 'Success',
                
            ],
        ]);
    }
    public function getBusRegisterGate(Request $request)
    {
        $serviceno = $request->get('gateRegister_serviceNo');
        $arrive= $request->get('gateRegister_isArrive');
        $inout = $request->get('gateRegister_inout');


        $getGate = GateRegister::with('bus','gate','user')->where('gateRegister_serviceNo','=',$serviceno)
        ->where('gateRegister_isArrive','=',$arrive)
        ->where('gateRegister_inout','=',$inout)
        ->get()->toArray();
        if(!$getGate){
           return $this->respondNotFound('Not Success');
        }
        return $this->respond([
            'data' => [
                'status' => 'Success',
                'gate_bus' => $getGate
                
            ],
        ]);
    }
    public function busState(Request $request)
    {
    	$data = [
    		'busState_serviceno' => $request->get('busState_serviceno'),
    		"busState_onoff" => $request->get('busState_onoff'),
    		"busState_busno" => $request->get('busState_busno'),
    		"busState_time" =>$request->get('busState_time'),
    		"busState_date"  =>$request->get('busState_date')
    		
    	];

    	$gate = BusState::create($data);

    	
    	return $this->respond([
    		'data' => [
                'status' => 'Success',
                
            ],
        ]);
    }
    public function getBusState(Request $request)
    {
        $date = $request->get('busState_date');
        $onoff = $request->get('busState_onoff');

        $state = BusState::with('bus')
        ->where('busState_date','=',$date)
        ->where('busState_onoff','=',$onoff)
        ->get()->toArray();
        if(!$state){
           return $this->respondNotFound('Not Success');
        }
        return $this->respond([
            'data' => [
                'status' => 'Success',
                'bus_state' => $state
                
            ],
        ]);

    }
    public function getGateUser(Request $request)
    {
        $name = $request->get('gatekeeper_accountName');
        $password = sha1($request->get('gatekeeper_password'));

    	$gate = GateKeeper::with('bus','busgate')->where('gatekeeper_accountName','=',$name)
        ->where('gatekeeper_password','=',$password)
        ->get()->toArray();

    	if(!$gate){
           return $this->respondNotFound('Not Success');
        }
        return $this->respond([
            'data' => [
                'status' => 'Success',
                'gate_keeper' => $gate
                
            ],
        ]);
    }
    public function getGate(Request $request)
    {
    	$gate = BusGate::get()->toArray();

    	return $this->respond([
    		'data' => [
                'status' => 'Success',
                'gate' => $gate
            ],
        ]);
    }
}

app/Http/Controllers/Backend/Api/GuzzleClient.php
<?php namespace App\Http\Controllers\Backend\Api;

use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Client;
use Illuminate\Http\Request;

class GuzzleClient
{
    public $client;

    protected $jsession;

    private $base_uri = "http://yangonbus.selfip.net:88/";

    private $login_url = 'StandardApiAction_login.action?';

    private $logout_url = 'StandardApiAction_logout.action?';

    protected $api_url = '';

    public function __construct()
    {
        $this->client = new Client(['base_uri' => $this->base_uri]);
    }



    public function login($userName, $password)
    {
        $data = [
            'account'   => $userName,
            'password'  => $password
        ];
        $response = $this->client->get($this->login_url,['query' => $data]);
        $data = json_decode($response->getBody(),true);
        $this->jsession = isset($data['jsession']) ? $data['jsession'] : '';
        return true;
    }


    public function logout()
    {
        $data = [
            'jsession'   => $this->jsession
        ];
        $response = $this->client->get($this->logout_url,['query' => $data]);
        $data = $response->getBody();
        echo $data;
    }
}

app/Http/Controllers/Backend/Api/SdeviceApiController.php
<?php namespace App\Http\Controllers\Backend\Api;


use Illuminate\Http\Request;
use App\Device;
use DB;
class SdeviceApiController extends ApiController
{ 
    private $user;
    private $password;

    private $db;

    function __construct(Request $request)
    {
      $user = $request->get('user');
      $password = $request->get('password');
      if ($user && $password) {
        $this->user = $user;
        $this->password = $password;
      }else{
        $this->respondWithError('Please check user name and password');
      }
      $this->db = DB::connection('sqlsrv');
    }

    public function index()
    { 
      $query = "select * from dbo.Device
                where ID in(select ud.DeviceID from dbo.UserData as uda
                join dbo.UsrDevice as ud on ud.UserID = uda.ID
                where uda.UserName ='$this->user' and uda.PassWord ='$this->password')";
      $devices = $this->db->select($query);
      return $this->respond([
        'total' => count($devices),
        'data' => $devices
      ]);
    }
}

app/Http/Controllers/Backend/Api/SdeviceController.php
<?php namespace App\Http\Controllers\Backend\Api;


use Illuminate\Http\Request;
use App\Device;

class SdeviceController extends ApiController
{
    public function index()
    {
        $devices = Device::all();
        echo $devices;
    }
}

app/Http/Controllers/Backend/Api/VehiclesApiController.php
<?php namespace App\Http\Controllers\Backend\Api;


use Illuminate\Http\Request;
use App\Bus;

class VehiclesApiController extends GuzzleClient
{
    protected $api_url = 'StandardApiAction_queryUserVehicle.action?';


    function __construct(Request $request)
    {
      parent::__construct();
      $user = $request->get('user');
      $password = $request->get('password');
      if ($user && $password) {
        $this->login($user,$password);
      }else{
        $ret = ['status' => 'fail','msg' => 'Unauthorize access.Please check user name and password!'];
        echo json_encode($ret);
      }
    }

    public function index()
    {
      $response = $this->client->get($this->api_url,['query' => [
          'jsession'  => $this->jsession
        ]]);
      $data = $response->getBody();

      echo $data;
    }
}

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BackendController extends Controller
{
    protected $model;

    protected $resourceName;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Bus;
use App\BusStop;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Backend\Traits\Authorizable;
class DashboardController extends Controller
{
    //use Authorizable;

    public function index()
    {   
        $buses = Bus::all();
        $busstops = BusStop::all();
        $data = [
          'totalBus'  => count($buses),
          'totalBusStop' => count($busstops)
        ];
        return view('backend.dashboard',compact('data'));
    }
}

resources/views/backend/bus/create.blade.php
@extends('backend.layout')

@section('content')
<div class="row">
  <div class="col-lg-12">
      <div class="card">
          <div class="card-header">
              <i class="fa fa-align-justify"></i> Create Bus
          </div>
          <div class="card-block">
            {!! Form::open(['route' => 'bus.store','method' => 'POST','class' => 'form-2orizontal']) !!}
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                   <label for="name" class="form-label">Bus Name</label>
                   <input type="text" name="name" class="form-control" value="{{old('name')}}" required="required" placeholder="Enter Bus Name">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                   <label for="operator" class="form-label">Operator</label>
                   <input type="text" name="operator" class="form-control" value="{{ old('operator') }}"  placeholder="Enter Operator">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                   <label for="password" class="form-label">Password</label>
                   <input type="text" name="password" id="password" class="form-control" value="{{ old('password') }}" placeholder="Enter Password">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                   <label for="user" class="form-label">User Name</label>
                   <input type="text" name="user" class="form-control" value="{{ old('user') }}" required="required" placeholder="Enter User Name">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                   <label for="server" class="form-label">Server</label>
                   <select name="server" class="form-control" required="required">
                     <option value="">Select Server</option>
                     <option value="yangonbus.selfip.net">yangonbus.selfip.net</option>
                     <option value="yangonbus2.selfip.net">yangonbus2.selfip.net</option>
                   </select>
                  </div>
                </div>
              </div>
              <hr>
            <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
            <a class="btn btn-default" href="{{ route('bus.index') }}" role="button">Cancel</a>
            {!! Form::close() !!}
          </div>
      </div>
  </div>
  <!--/.col-->
</div>
@endsection


@push('scripts')
<script>
</script>
@endpush

resources/views/backend/bus/index.blade.php
@extends('backend.layout')

@section('content')
<div class="row">
  <div class="col-lg-12">
      <div class="card">
          <div class="card-header">
              <i class="fa fa-bus"></i> Bus
              <div class="pull-right">
                  <a href="{{ route('bus.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Add</a>
              </div>
          </div>
          <div class="card-block">
              <table class="table table-bordered table-striped table-condensed datatables">
                  <thead>
                      <tr>
                          <th width="5%">No</th>
                          <th>Name</th>
                          <th>User</th>
                          <th>Server</th>
                          <th>Action</th>
                      </tr>
                  </thead>
                  <tbody>
                      @foreach ($buses as $key => $bus)
                        <tr>
                          <td> {{ ++$key }}</td>
                          <td>{{ $bus->name}}</td>
                          <td>{{ $bus->user}}</td>
                          <td>{{ $bus->server}}</td>
                          <td>
                            <a href="{{ route('bus.edit',['id' => $bus->id]) }}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i> Edit</a>
                            {!! Form::open([
                                'method'=>'DELETE',
                                'url' => route('bus.destroy',['bus' => $bus]),
                                'style' => 'display:inline'
                            ]) !!}
                                {!! Form::button('<i class="fa fa-trash-o" aria-hidden="true"></i> Delete', array(
                                        'type' => 'submit',
                                        'class' => 'btn btn-danger btn-sm',
                                        'title' => 'Delete',
                                        'onclick'=>'return confirm("Confirm delete?")'
                                )) !!}
                            {!! Form::close() !!}
                          </td>
                        </tr>
                      @endforeach
                  </tbody>
              </table>
              <nav>

              </nav>
          </div>
      </div>
  </div>
  <!--/.col-->
</div>
@endsection

resources/views/backend/bus/update.blade.php
@extends('backend.layout')

@section('content')
<div class="row">
  <div class="col-lg-12">
      <div class="card">
          <div class="card-header">
              <i class="fa fa-align-justify"></i> Update Bus
          </div>
          <div class="card-block">
         {!! Form::open(['route' => (['bus.update',$bus]),'method' => 'PUT','class' => 'form-2orizontal','autocomplete' => 'false']) !!}
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                   <label for="name" class="form-label">Name</label>
                   <input type="text" name="name" class="form-control" value="{{ $bus->name }}" required="required" placeholder="Enter Bus Name">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                   <label for="operator" class="form-label">Operator</label>
                   <input type="text" name="operator" class="form-control" value="{{ $bus->operator }}" placeholder="Enter Operator">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                   <label for="password" class="form-label">Password</label>
                   <input type="text" name="password" id="password" class="form-control" autocomplete="false" value="{{ $bus->password }}" placeholder="Enter Password">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                   <label for="user" class="form-label">User Nmae</label>
                   <input type="text" name="user" class="form-control" value="{{ $bus->user }}" required="required" placeholder="Enter User Name">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                   <label for="server" class="form-label">Server</label>
                   <select name="server" class="form-control" required="required">
                     <option value="">Select Server</option>
                     <option value="yangonbus.selfip.net" @if($bus->server == 'yangonbus.selfip.net') selected @endif >yangonbus.selfip.net</option>
                     <option value="yangonbus2.selfip.net" @if($bus->server == 'yangonbus2.selfip.net') selected @endif>yangonbus2.selfip.net</option>
                   </select>
                  </div>
                </div>
              </div>
              <hr>
            <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Update</button>
            <a class="btn btn-default" href="{{ route('bus.index') }}" role="button">Cancel</a>
            {!! Form::close() !!}
          </div>
      </div>
  </div>
  <!--/.col-->
</div>
@endsection



@push('scripts')
<script>

/* $('#bus-stops').select2({
    tags: true
 });

$("#bus-stops").on("select2:select", function (evt) {
  var element = evt.params.data.element;
  var $element = $(element);

  $element.detach();
  $(this).append($element);
  $(this).trigger("change");
});*/

</script>
@endpush